version: '3.8'

services:
  php:
    build: .
    container_name: tracker
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: testdb
    depends_on:
      - db

  site1:
    build: .
    container_name: site1
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  
  site2:
    build: .
    container_name: site2
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
